name: orchid
description: Silicon Valley (Season 4)

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.9.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  badges: 1.1.6
  # XXX: use https://pub.dev/packages/firebase_ml_vision
  # that said, this library has been *discontinued*
  # this library can be upgraded to at least 3.0.1
  barcode_scan: 2.0.2
  cupertino_icons: 1.0.2
  dartjsengine: 1.0.1
  dotted_border: 1.0.7
  email_validator: 1.0.6
  flare_flutter: 2.0.6
  flutter:
    sdk: flutter
  flutter_cupertino_localizations: 1.0.1
  # XXX: our code is incompatible with 1.0+
  flutter_html: 0.11.1
  flutter_localizations:
    sdk: flutter
  # XXX: this doesn't support MacOS
  #flutter_secure_storage: 3.3.5
  flutter_svg: 0.19.2+1
  font_awesome_flutter: 8.11.0
  http: 0.12.2
  in_app_purchase:
    path: in_app_purchase
  percent_indicator: 2.1.8
  pointycastle: 1.0.2
  provider: 4.3.2+3
  qr_flutter: 3.2.0
  rxdart: 0.25.0
  shared_preferences: 0.5.12+4
  sqflite: 1.3.2+1
  url_launcher: 5.7.10
  uuid: 2.2.2
  web3dart: 1.2.3
# STOP ADDING ENTRIES TO THE END OF THIS ***ALPHABATIZED*** LIST

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/docs/
    - assets/docs/help/
    - assets/flare/
    - assets/images/
    - assets/svg/

flutter_intl:
  enabled: true
