name: CI
on: [push]
jobs:



  build-flutter:
    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v2
    - name: env/setup
      run: env/setup.sh
    - name: git submodule
      run: env/submodule.sh --jobs 3

    - name: make skeleton
      run: ./app-flutter.sh orchid
