name: CI
on: [push]
jobs:



  build-flutter:
    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v2
    - name: env/setup
      run: env/setup.sh
    - name: git submodule
      run: env/submodule.sh --jobs 3

    - name: make skeleton
      run: ./app-flutter.sh orchid



  build-ios-app:
    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v2
    - name: env/setup
      run: env/setup.sh
    - name: git submodule
      run: env/submodule.sh --jobs 3

    - name: make iOS .ipa
      run: debug=ldid make -j3 -C app-ios precache='--no-android'


  build-and-app:
    runs-on: ubuntu-latest

    steps:

    - name: rm -rf /opt
      run: sudo rm -rf /opt

    - uses: actions/checkout@v2
    - name: env/setup
      run: env/setup.sh
    - name: git submodule
      run: env/submodule.sh --jobs 3

    - name: make Android .apk
      run: make -j3 -C app-android precache='--no-ios'
    - uses: actions/upload-artifact@v1
      with:
        name: orchid-apk
        path: app-android/out-and/Orchid.apk
        #path: app-android/build/outputs/apk/release/app-android-release-unsigned.apk



  build-mac-app:
    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v2
    - name: env/setup
      run: env/setup.sh
    - name: git submodule
      run: env/submodule.sh --jobs 3

    - name: make macOS .app
      run: debug=ldid make -j3 -C app-macos precache='--no-android --no-ios --macos'


  build-mac-snd:
    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v2
    - name: env/setup
      run: env/setup.sh
    - name: git submodule
      run: env/submodule.sh --jobs 3

    - name: make macOS sender
      run: make -j3 -C eth-sender
    - uses: actions/upload-artifact@v1
      with:
        name: cj-mac
        path: eth-sender/out-mac/x86_64/cj


  build-mac-cli:
    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v2
    - name: env/setup
      run: env/setup.sh
    - name: git submodule
      run: env/submodule.sh --jobs 3

    - name: make macOS client
      run: make -j3 -C cli-shared
    - uses: actions/upload-artifact@v1
      with:
        name: orchidcd-mac
        path: cli-shared/out-mac/x86_64/orchidcd


  build-mac-srv:
    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v2
    - name: env/setup
      run: env/setup.sh
    - name: git submodule
      run: env/submodule.sh --jobs 3

    - name: make macOS server
      # XXX: v8 cannot be compiled using Xcode due to something I haven't spent the time to investigate :(
      # exception specification of explicitly defaulted copy constructor does not match the calculated one
      run: debug=crossndk make -j3 -C srv-shared
    - uses: actions/upload-artifact@v1
      with:
        name: orchidd-mac
        path: srv-shared/out-mac/x86_64/orchidd

    - name: git status
      run: git status



  build-win-app:
    runs-on: ubuntu-latest

    steps:

    - name: install mingw-w64
      run: DEBIAN_FRONTEND=noninteractive sudo -EH apt-get -y install mingw-w64

    - uses: actions/checkout@v2
    - name: env/setup
      run: env/setup.sh
    - name: git submodule
      run: env/submodule.sh --jobs 3

    - name: setup plugins
      run: debug=crossndk make -j3 -C app-windows ./env/dotdot/gui-orchid/.flutter-plugins
    - name: make Windows app
      run: make -j3 -C app-windows target=win precache='--no-android --no-ios --windows -a'
    - uses: actions/upload-artifact@v1
      with:
        name: orchid-win
        path: app-windows/out-win/package


  build-win-cli:
    runs-on: ubuntu-latest

    steps:

    - name: install mingw-w64
      run: DEBIAN_FRONTEND=noninteractive sudo -EH apt-get -y install mingw-w64

    - uses: actions/checkout@v2
    - name: env/setup
      run: env/setup.sh
    - name: git submodule
      run: env/submodule.sh --jobs 3

    - name: make Windows client
      run: make -j3 -C cli-shared target=win
    - uses: actions/upload-artifact@v1
      with:
        name: orchidcd-win
        path: cli-shared/out-win/x86_64/orchidcd.exe


  build-win-srv:
    runs-on: macos-latest

    steps:

    - name: install mingw-w64
      run: brew install mingw-w64 coreutils

    - uses: actions/checkout@v2
    - name: env/setup
      run: env/setup.sh
    - name: git submodule
      run: env/submodule.sh --jobs 3

    - name: make Windows server
      run: make -j3 -C srv-shared target=win
    - uses: actions/upload-artifact@v1
      with:
        name: orchidd-w64
        path: srv-shared/out-win/x86_64/orchidd.exe

    - name: git status
      run: git status



  build-lnx-app:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: env/setup
      run: env/setup.sh
    - name: git submodule
      run: env/submodule.sh --jobs 3

    - name: setup plugins
      run: debug=crossndk make -j3 -C app-linux ./env/dotdot/gui-orchid/.flutter-plugins
    - name: make Linux app
      run: debug=crossndk make -j3 -C app-linux precache='--no-android --no-ios --linux'
    - uses: actions/upload-artifact@v1
      with:
        name: orchid-lnx
        path: app-linux/out-lnx/package


  build-lnx-cli:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: env/setup
      run: env/setup.sh
    - name: git submodule
      run: env/submodule.sh --jobs 3

    - name: make Linux client
      run: debug=crossndk make -j3 -C cli-shared
    - uses: actions/upload-artifact@v1
      with:
        name: orchidcd-lnx
        path: cli-shared/out-lnx/x86_64/orchidcd


  build-lnx-srv:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: env/setup
      run: env/setup.sh
    - name: git submodule
      run: env/submodule.sh --jobs 3

    - name: make Linux server
      run: debug=crossndk make -j3 -C srv-shared

    - name: git status
      run: git status


  build-lnx-dkr:
    runs-on: ubuntu-latest

    steps:

    - name: rm -rf /opt
      run: sudo rm -rf /opt

    - uses: actions/checkout@v2
    - name: env/setup
      run: env/setup-git.sh
    - name: git submodule
      run: env/submodule.sh --jobs 3

    - name: make Linux server
      run: cd srv-shared && ./docker.sh


  build-lnx-bld:
    runs-on: ubuntu-latest

    steps:

    - name: rm -rf /opt
      run: sudo rm -rf /opt

    - uses: actions/checkout@v2

    - name: make Linux server
      run: docker build --build-arg GIT_REPOSITORY=https://github.com/${{ github.repository }}.git --build-arg GIT_COMMIT=${{ github.sha }} --build-arg GIT_SETUP=env/setup-git.sh -t orchidd:latest srv-docker
    - name: docker save
      run: docker save -o orchidd.tar orchidd:latest
    - uses: actions/upload-artifact@v1
      with:
        name: orchidd-dkr
        path: orchidd.tar


  build-lnx-mac:
    runs-on: macos-latest

    steps:

    - name: install NDK r21
      run: echo y | sudo -EH "${ANDROID_HOME}/tools/bin/sdkmanager" "ndk;21.3.6528147" >/dev/null

    - uses: actions/checkout@v2
    - name: env/setup
      run: env/setup.sh
    - name: git submodule
      run: env/submodule.sh --jobs 3

    - name: make Linux server
      run: ANDROID_NDK_HOME=~/Library/Android/sdk/ndk/21.3.6528147 make -j3 -C srv-shared target=lnx
    - uses: actions/upload-artifact@v1
      with:
        name: orchidd-lnx
        path: srv-shared/out-lnx/x86_64/orchidd


  build-lnx-bad:
    runs-on: ubuntu-20.04

    steps:

    - uses: actions/checkout@v2
    - name: env/setup
      run: env/setup.sh
    - name: git submodule
      run: env/submodule.sh --jobs 3

    - name: make Linux server
      run: make -j3 -C srv-shared


  build-lnx-all:
    needs: [build-lnx-mac, build-lnx-bld]
    runs-on: ubuntu-latest

    steps:

    - name: download orchidd-dkr
      uses: actions/download-artifact@v2
      with:
        name: orchidd-dkr
    - name: extract docker image
      run: tar -xvf orchidd.tar
    - name: extract docker layer
      run: tar -xvf "$(jq -r '.[0].Layers | .[]' manifest.json | tail -n1)"

    - name: download orchidd-lnx
      uses: actions/download-artifact@v2
      with:
        name: orchidd-lnx
    - name: verify reproduction
      run: diff -u <(xxd usr/sbin/orchidd) <(xxd orchidd)



